spring:
    datasource:
        url: jdbc:mysql://localhost:3306/WALP?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&useSSL=false
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                jdbc.batch_size: 1000
                order_inserts: true
                order_updates: true
                generate_statistics: false
                show_sql: true
        hibernate:
            ddl-auto: create

parser:
    log:
        separator : "\\|"
        date:
            format: "yyyy-MM-dd HH:mm:ss.SSS"
