spring:
    datasource:
        url: jdbc:mysql://localhost:3306/WALP
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
            show-sql: true